# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela-deposito.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Deposito(object):
    def setupUi(self, Tela_Deposito):
        Tela_Deposito.setObjectName("Tela_Deposito")
        Tela_Deposito.resize(340, 340)
        Tela_Deposito.setMinimumSize(QtCore.QSize(340, 340))
        Tela_Deposito.setMaximumSize(QtCore.QSize(340, 340))
        Tela_Deposito.setStyleSheet("QFrame {\n"
"    color: rgb(40, 40, 40)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Tela_Deposito)
        self.centralwidget.setMinimumSize(QtCore.QSize(340, 340))
        self.centralwidget.setMaximumSize(QtCore.QSize(340, 340))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(340, 340))
        self.frame.setMaximumSize(QtCore.QSize(340, 340))
        self.frame.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelBanco = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelBanco.setEnabled(True)
        self.labelBanco.setMinimumSize(QtCore.QSize(0, 40))
        self.labelBanco.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.labelBanco.setFont(font)
        self.labelBanco.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelBanco.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBanco.setObjectName("labelBanco")
        self.horizontalLayout.addWidget(self.labelBanco)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 289, 341, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Voltar = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Voltar.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Voltar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Voltar.setFont(font)
        self.pushButton_Voltar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.horizontalLayout_2.addWidget(self.pushButton_Voltar)
        self.pushButton_Depositar = QtWidgets.QPushButton(self.frame)
        self.pushButton_Depositar.setGeometry(QtCore.QRect(120, 250, 100, 40))
        self.pushButton_Depositar.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Depositar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Depositar.setFont(font)
        self.pushButton_Depositar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_Depositar.setObjectName("pushButton_Depositar")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 130, 341, 51))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_Valor = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Valor.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Valor.sizePolicy().hasHeightForWidth())
        self.lineEdit_Valor.setSizePolicy(sizePolicy)
        self.lineEdit_Valor.setMinimumSize(QtCore.QSize(280, 40))
        self.lineEdit_Valor.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
        self.lineEdit_Valor.setMaxLength(60)
        self.lineEdit_Valor.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_Valor.setObjectName("lineEdit_Valor")
        self.horizontalLayout_6.addWidget(self.lineEdit_Valor)
        self.labelLogin = QtWidgets.QLabel(self.frame)
        self.labelLogin.setEnabled(True)
        self.labelLogin.setGeometry(QtCore.QRect(0, 70, 341, 40))
        self.labelLogin.setMinimumSize(QtCore.QSize(0, 40))
        self.labelLogin.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelLogin.setFont(font)
        self.labelLogin.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLogin.setObjectName("labelLogin")
        self.verticalLayout_2.addWidget(self.frame)
        Tela_Deposito.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_Deposito)
        QtCore.QMetaObject.connectSlotsByName(Tela_Deposito)

    def retranslateUi(self, Tela_Deposito):
        _translate = QtCore.QCoreApplication.translate
        Tela_Deposito.setWindowTitle(_translate("Tela_Deposito", "V&V Depósito"))
        self.labelBanco.setText(_translate("Tela_Deposito", "V&V Bank"))
        self.pushButton_Voltar.setText(_translate("Tela_Deposito", "Voltar"))
        self.pushButton_Depositar.setText(_translate("Tela_Deposito", "Depositar"))
        self.lineEdit_Valor.setPlaceholderText(_translate("Tela_Deposito", "R$"))
        self.labelLogin.setText(_translate("Tela_Deposito", "Depósito"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Deposito = QtWidgets.QMainWindow()
    ui = Ui_Tela_Deposito()
    ui.setupUi(Tela_Deposito)
    Tela_Deposito.show()
    sys.exit(app.exec_())
