# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela-cadastrar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Cadastro(object):
    def setupUi(self, Tela_Cadastro):
        Tela_Cadastro.setObjectName("Tela_Cadastro")
        Tela_Cadastro.resize(340, 340)
        Tela_Cadastro.setMinimumSize(QtCore.QSize(340, 340))
        Tela_Cadastro.setMaximumSize(QtCore.QSize(340, 340))
        Tela_Cadastro.setStyleSheet("QFrame {\n"
"    color: rgb(40, 40, 40)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Tela_Cadastro)
        self.centralwidget.setMinimumSize(QtCore.QSize(340, 340))
        self.centralwidget.setMaximumSize(QtCore.QSize(340, 340))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(340, 340))
        self.frame.setMaximumSize(QtCore.QSize(340, 340))
        self.frame.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_Voltar = QtWidgets.QPushButton(self.frame)
        self.pushButton_Voltar.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Voltar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Voltar.setFont(font)
        self.pushButton_Voltar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.horizontalLayout_3.addWidget(self.pushButton_Voltar)
        self.gridLayout.addLayout(self.horizontalLayout_3, 8, 0, 1, 1)
        self.labelBanco = QtWidgets.QLabel(self.frame)
        self.labelBanco.setEnabled(True)
        self.labelBanco.setMinimumSize(QtCore.QSize(0, 40))
        self.labelBanco.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.labelBanco.setFont(font)
        self.labelBanco.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelBanco.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBanco.setObjectName("labelBanco")
        self.gridLayout.addWidget(self.labelBanco, 0, 0, 1, 1)
        self.labelCadastro = QtWidgets.QLabel(self.frame)
        self.labelCadastro.setEnabled(True)
        self.labelCadastro.setMinimumSize(QtCore.QSize(0, 40))
        self.labelCadastro.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCadastro.setFont(font)
        self.labelCadastro.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelCadastro.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCadastro.setObjectName("labelCadastro")
        self.gridLayout.addWidget(self.labelCadastro, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Cadastrar = QtWidgets.QPushButton(self.frame)
        self.pushButton_Cadastrar.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Cadastrar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Cadastrar.setFont(font)
        self.pushButton_Cadastrar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_Cadastrar.setObjectName("pushButton_Cadastrar")
        self.horizontalLayout_2.addWidget(self.pushButton_Cadastrar)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit_Nome = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Nome.setMinimumSize(QtCore.QSize(280, 40))
        self.lineEdit_Nome.setMaximumSize(QtCore.QSize(280, 40))
        self.lineEdit_Nome.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_Nome.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
        self.lineEdit_Nome.setObjectName("lineEdit_Nome")
        self.horizontalLayout_7.addWidget(self.lineEdit_Nome)
        self.gridLayout.addLayout(self.horizontalLayout_7, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_Sobrenome = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Sobrenome.setMinimumSize(QtCore.QSize(280, 40))
        self.lineEdit_Sobrenome.setMaximumSize(QtCore.QSize(280, 40))
        self.lineEdit_Sobrenome.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
        self.lineEdit_Sobrenome.setObjectName("lineEdit_Sobrenome")
        self.horizontalLayout_6.addWidget(self.lineEdit_Sobrenome)
        self.gridLayout.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_Senha = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Senha.sizePolicy().hasHeightForWidth())
        self.lineEdit_Senha.setSizePolicy(sizePolicy)
        self.lineEdit_Senha.setMinimumSize(QtCore.QSize(280, 40))
        self.lineEdit_Senha.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
        self.lineEdit_Senha.setMaxLength(60)
        self.lineEdit_Senha.setObjectName("lineEdit_Senha")
        self.horizontalLayout_5.addWidget(self.lineEdit_Senha)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_CPF = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_CPF.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_CPF.sizePolicy().hasHeightForWidth())
        self.lineEdit_CPF.setSizePolicy(sizePolicy)
        self.lineEdit_CPF.setMinimumSize(QtCore.QSize(280, 40))
        self.lineEdit_CPF.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(55, 55, 55);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(94, 53, 177);\n"
"}")
        self.lineEdit_CPF.setMaxLength(60)
        self.lineEdit_CPF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit_CPF.setObjectName("lineEdit_CPF")
        self.horizontalLayout_4.addWidget(self.lineEdit_CPF)
        self.gridLayout.addLayout(self.horizontalLayout_4, 4, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        Tela_Cadastro.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_Cadastro)
        QtCore.QMetaObject.connectSlotsByName(Tela_Cadastro)

    def retranslateUi(self, Tela_Cadastro):
        _translate = QtCore.QCoreApplication.translate
        Tela_Cadastro.setWindowTitle(_translate("Tela_Cadastro", "V&V Cadastro"))
        self.pushButton_Voltar.setText(_translate("Tela_Cadastro", "Voltar"))
        self.labelBanco.setText(_translate("Tela_Cadastro", "V&V Bank"))
        self.labelCadastro.setText(_translate("Tela_Cadastro", "Cadastro"))
        self.pushButton_Cadastrar.setText(_translate("Tela_Cadastro", "Cadastrar"))
        self.lineEdit_Nome.setPlaceholderText(_translate("Tela_Cadastro", "NOME"))
        self.lineEdit_Sobrenome.setPlaceholderText(_translate("Tela_Cadastro", "SOBRENOME"))
        self.lineEdit_Senha.setPlaceholderText(_translate("Tela_Cadastro", "SENHA"))
        self.lineEdit_CPF.setPlaceholderText(_translate("Tela_Cadastro", "CPF"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Cadastro = QtWidgets.QMainWindow()
    ui = Ui_Tela_Cadastro()
    ui.setupUi(Tela_Cadastro)
    Tela_Cadastro.show()
    sys.exit(app.exec_())
