# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela-usuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Usuario(object):
    def setupUi(self, Tela_Usuario):
        Tela_Usuario.setObjectName("Tela_Usuario")
        Tela_Usuario.resize(340, 340)
        Tela_Usuario.setMinimumSize(QtCore.QSize(340, 340))
        Tela_Usuario.setMaximumSize(QtCore.QSize(340, 340))
        Tela_Usuario.setStyleSheet("QFrame {\n"
"    color: rgb(40, 40, 40)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Tela_Usuario)
        self.centralwidget.setMinimumSize(QtCore.QSize(340, 340))
        self.centralwidget.setMaximumSize(QtCore.QSize(340, 340))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(340, 340))
        self.frame.setMaximumSize(QtCore.QSize(340, 340))
        self.frame.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelSaldacao = QtWidgets.QLabel(self.frame)
        self.labelSaldacao.setGeometry(QtCore.QRect(10, 80, 81, 40))
        self.labelSaldacao.setMinimumSize(QtCore.QSize(0, 40))
        self.labelSaldacao.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setBold(True)
        font.setWeight(75)
        self.labelSaldacao.setFont(font)
        self.labelSaldacao.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelSaldacao.setObjectName("labelSaldacao")
        self.lineEdit_Nome = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Nome.setGeometry(QtCore.QRect(90, 80, 200, 40))
        self.lineEdit_Nome.setMinimumSize(QtCore.QSize(200, 40))
        self.lineEdit_Nome.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Nome.setFont(font)
        self.lineEdit_Nome.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(40, 40, 40);;\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_Nome.setText("")
        self.lineEdit_Nome.setReadOnly(True)
        self.lineEdit_Nome.setObjectName("lineEdit_Nome")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelBanco = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelBanco.setEnabled(True)
        self.labelBanco.setMinimumSize(QtCore.QSize(0, 40))
        self.labelBanco.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.labelBanco.setFont(font)
        self.labelBanco.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelBanco.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBanco.setObjectName("labelBanco")
        self.horizontalLayout.addWidget(self.labelBanco)
        self.labelSaldo = QtWidgets.QLabel(self.frame)
        self.labelSaldo.setGeometry(QtCore.QRect(10, 110, 81, 40))
        self.labelSaldo.setMinimumSize(QtCore.QSize(0, 40))
        self.labelSaldo.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setBold(True)
        font.setWeight(75)
        self.labelSaldo.setFont(font)
        self.labelSaldo.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelSaldo.setObjectName("labelSaldo")
        self.lineEdit_Saldo = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_Saldo.setGeometry(QtCore.QRect(90, 110, 200, 40))
        self.lineEdit_Saldo.setMinimumSize(QtCore.QSize(200, 40))
        self.lineEdit_Saldo.setMaximumSize(QtCore.QSize(200, 40))
        font = QtGui.QFont()
        font.setFamily("Fira Code")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_Saldo.setFont(font)
        self.lineEdit_Saldo.setStyleSheet("QLineEdit {\n"
"    border: 2px solid rgb(40, 40, 40);;\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_Saldo.setText("")
        self.lineEdit_Saldo.setReadOnly(True)
        self.lineEdit_Saldo.setObjectName("lineEdit_Saldo")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 160, 341, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_TelaDeposito = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_TelaDeposito.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_TelaDeposito.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_TelaDeposito.setFont(font)
        self.pushButton_TelaDeposito.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_TelaDeposito.setObjectName("pushButton_TelaDeposito")
        self.gridLayout.addWidget(self.pushButton_TelaDeposito, 0, 0, 1, 1)
        self.pushButton_TelaSaque = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_TelaSaque.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_TelaSaque.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_TelaSaque.setFont(font)
        self.pushButton_TelaSaque.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_TelaSaque.setObjectName("pushButton_TelaSaque")
        self.gridLayout.addWidget(self.pushButton_TelaSaque, 1, 0, 1, 1)
        self.pushButton_TelaTransferencia = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_TelaTransferencia.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_TelaTransferencia.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_TelaTransferencia.setFont(font)
        self.pushButton_TelaTransferencia.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_TelaTransferencia.setObjectName("pushButton_TelaTransferencia")
        self.gridLayout.addWidget(self.pushButton_TelaTransferencia, 0, 1, 1, 1)
        self.pushButton_TelaHistorico = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_TelaHistorico.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_TelaHistorico.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_TelaHistorico.setFont(font)
        self.pushButton_TelaHistorico.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_TelaHistorico.setObjectName("pushButton_TelaHistorico")
        self.gridLayout.addWidget(self.pushButton_TelaHistorico, 1, 1, 1, 1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 269, 341, 71))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Voltar = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Voltar.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Voltar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Voltar.setFont(font)
        self.pushButton_Voltar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.horizontalLayout_2.addWidget(self.pushButton_Voltar)
        self.verticalLayout_2.addWidget(self.frame)
        Tela_Usuario.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_Usuario)
        QtCore.QMetaObject.connectSlotsByName(Tela_Usuario)

    def retranslateUi(self, Tela_Usuario):
        _translate = QtCore.QCoreApplication.translate
        Tela_Usuario.setWindowTitle(_translate("Tela_Usuario", "V&V Bank"))
        self.labelSaldacao.setText(_translate("Tela_Usuario", "Olá, sr(a):"))
        self.lineEdit_Nome.setPlaceholderText(_translate("Tela_Usuario", "FULANO"))
        self.labelBanco.setText(_translate("Tela_Usuario", "V&V Bank"))
        self.labelSaldo.setText(_translate("Tela_Usuario", "Saldo: R$"))
        self.lineEdit_Saldo.setPlaceholderText(_translate("Tela_Usuario", "100,00"))
        self.pushButton_TelaDeposito.setText(_translate("Tela_Usuario", "Depósito"))
        self.pushButton_TelaSaque.setText(_translate("Tela_Usuario", "Saque"))
        self.pushButton_TelaTransferencia.setText(_translate("Tela_Usuario", "Transferência"))
        self.pushButton_TelaHistorico.setText(_translate("Tela_Usuario", "Histórico"))
        self.pushButton_Voltar.setText(_translate("Tela_Usuario", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Usuario = QtWidgets.QMainWindow()
    ui = Ui_Tela_Usuario()
    ui.setupUi(Tela_Usuario)
    Tela_Usuario.show()
    sys.exit(app.exec_())
