# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela-extrato.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tela_Extrato(object):
    def setupUi(self, Tela_Extrato):
        Tela_Extrato.setObjectName("Tela_Extrato")
        Tela_Extrato.resize(340, 340)
        Tela_Extrato.setMinimumSize(QtCore.QSize(340, 340))
        Tela_Extrato.setMaximumSize(QtCore.QSize(340, 340))
        Tela_Extrato.setStyleSheet("QFrame {\n"
"    color: rgb(40, 40, 40)\n"
"}")
        self.centralwidget = QtWidgets.QWidget(Tela_Extrato)
        self.centralwidget.setMinimumSize(QtCore.QSize(340, 340))
        self.centralwidget.setMaximumSize(QtCore.QSize(340, 340))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(340, 340))
        self.frame.setMaximumSize(QtCore.QSize(340, 340))
        self.frame.setStyleSheet("background-color: rgb(40, 40, 40);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 341, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelBanco = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.labelBanco.setEnabled(True)
        self.labelBanco.setMinimumSize(QtCore.QSize(0, 40))
        self.labelBanco.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.labelBanco.setFont(font)
        self.labelBanco.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelBanco.setAlignment(QtCore.Qt.AlignCenter)
        self.labelBanco.setObjectName("labelBanco")
        self.horizontalLayout.addWidget(self.labelBanco)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 289, 341, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Voltar = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Voltar.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton_Voltar.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Unispace")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Voltar.setFont(font)
        self.pushButton_Voltar.setStyleSheet("QPushButton {\n"
"    \n"
"    background-color: rgb(94, 53, 177);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    \n"
"    background-color: rgb(60, 60, 60);\n"
"    border: 2px solid rgb(70,70,70);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    \n"
"    background-color: rgb(40, 40, 40);\n"
"    border: 2px solid rgb(81, 45, 168);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_Voltar.setObjectName("pushButton_Voltar")
        self.horizontalLayout_2.addWidget(self.pushButton_Voltar)
        self.labelExtrato = QtWidgets.QLabel(self.frame)
        self.labelExtrato.setEnabled(True)
        self.labelExtrato.setGeometry(QtCore.QRect(0, 60, 341, 40))
        self.labelExtrato.setMinimumSize(QtCore.QSize(0, 40))
        self.labelExtrato.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelExtrato.setFont(font)
        self.labelExtrato.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.labelExtrato.setAlignment(QtCore.Qt.AlignCenter)
        self.labelExtrato.setObjectName("labelExtrato")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 100, 361, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.textEdit_Historico = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit_Historico.setStyleSheet("QTextEdit {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.textEdit_Historico.setReadOnly(True)
        self.textEdit_Historico.setObjectName("textEdit_Historico")
        self.horizontalLayout_5.addWidget(self.textEdit_Historico)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addWidget(self.frame)
        Tela_Extrato.setCentralWidget(self.centralwidget)

        self.retranslateUi(Tela_Extrato)
        QtCore.QMetaObject.connectSlotsByName(Tela_Extrato)

    def retranslateUi(self, Tela_Extrato):
        _translate = QtCore.QCoreApplication.translate
        Tela_Extrato.setWindowTitle(_translate("Tela_Extrato", "V&V Extrato"))
        self.labelBanco.setText(_translate("Tela_Extrato", "V&V Bank"))
        self.pushButton_Voltar.setText(_translate("Tela_Extrato", "Voltar"))
        self.labelExtrato.setText(_translate("Tela_Extrato", "EXTRATO"))
        self.textEdit_Historico.setHtml(_translate("Tela_Extrato", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">asldkfjlaskdj flaksdj flaksdjflkasdjflaksd lfaskjd flaskdjf laskd faskdjflaskdfjlask fasldkfjasldkf lasdjflaskdjflaskdjflaskdjflaskd jflaskd flaskd jflaskdfj laskdfjalsdfjlasdkfjasdfasdfkjlasdkjflaskdjflaksdjflkasdjflaksjdflaksdjflaksdjflkasjdflaskdjfoaskjdfhgowergjwejgewqitjqwpogweiuqwrtwqçgewrjgijglkdsjfghopdsifjgpergçlfkgsdp´fogçewrlgkdfogipeorgçldfkgpdsofigçdlsfjgpsdkfjig-orglç~,wrçglkdfpgokdsfçlgkçerlgdpfogjçsdflgk~]sdlfkgpdijghdlskfg~dlfsigpéirgçldg~sdkfgpksdjçflglepogpkwrngçdslfgh´sdlkfgosdihgpsdfga sd flaskdflaskdjflaksdjflasd flsadkfjlaskdjf laskdjflaskdjflaskd foaskdfjlskfjlaskdflsakdjflaskdjflsakdfjlsakdjflaskdfjlaskdf lsakdfjlaskdfjlaskdfjlasdkfjlasd lsdakfjalskdfjlaskdfjlaskd flaskdfjlaskdjflaskdjflsakdjflaskdjf </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">asdfasdf</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tela_Extrato = QtWidgets.QMainWindow()
    ui = Ui_Tela_Extrato()
    ui.setupUi(Tela_Extrato)
    Tela_Extrato.show()
    sys.exit(app.exec_())
