

clientes = """CREATE TABLE IF NOT EXISTS clientes(
				id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				nome text NOT NULL,
				sobrenome text NOT NULL,
				cpf text NOT NULL
				);"""

contas = """CREATE TABLE IF NOT EXISTS contas(
				id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				id_pessoa int NOT NULL,
				saldo float NOT NULL,
				senha text NOT NULL,
				limite float NOT NULL
				);"""

historicos = """CREATE TABLE IF NOT EXISTS historicos(
				id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				id_conta int NOT NULL,
				transacao text NOT NULL
				);"""



busca_cliente = """SELECT * FROM clientes WHERE cpf = '{}'"""

cadastrar_cliente = """INSERT INTO clientes(nome, sobrenome, cpf) VALUES('{}','{}','{}')"""

busca_conta = """SELECT * FROM contas, clientes WHERE contas.id_pessoa = clientes.id AND clientes.cpf = '{}'"""

cadastrar_conta = """INSERT INTO contas(id_pessoa, saldo, senha, limite) VALUES({},{},'{}',{})"""

autentica_senha = """SELECT * FROM contas WHERE contas.id = {} and contas.senha = '{}'"""

busca_valores = """SELECT clientes.nome, contas.saldo, contas.limite FROM clientes, contas WHERE contas.id = {} AND contas.id_pessoa = clientes.id"""


cadastrar_historico = """INSERT INTO historicos(id_conta, transacao) VALUES({},'{}')"""

mostra_historico = """SELECT historicos.transacao FROM historicos WHERE historicos.id_conta = {}"""

atualizar_saldo = """UPDATE contas SET saldo = {} WHERE id = {}"""
